services:
  # Backend API
  - type: web
    name: cineverse-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: DB_HOST
        value: mysql-2848d11-ummekulsum0069-8dd8.g.aivencloud.com
      - key: DB_PORT
        value: 16663
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
    
  # Frontend
  - type: web
    name: cineverse-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
