services:
  # Backend API
  - type: web
    name: cineverse-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: DB_HOST
        value: mysql-2848d11-ummekulsum0069-8dd8.g.aivencloud.com
      - key: DB_PORT
        value: 16663
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
